/*!
  \file linear_algebra_test.comp
  \author Sho Ikeda
  \brief Test kernel for matrix-vector multiplication and vector accumulation
  \copyright Copyright (c) 2026 Advanced Micro Devices, Inc. All Rights Reserved.

  SPDX-License-Identifier: MIT
*/

#include "mlp.hlsl"

ByteAddressBuffer InputBuffer;
RWByteAddressBuffer OutputBuffer;
ByteAddressBuffer WeightBuffer;
ByteAddressBuffer BiasBuffer;

// TODO. Fix me
#define BIAS_VECTOR_ALIGNMENT 128

template <typename Type>
void testLinearAlgebraMul(const uint threadId)
{
  const dx::linalg::ComponentEnum elemType = mininn::impl::TypeTraits<Type>::COMPONENT_TYPE;
  const uint numTasks = MINIDXNN_NUM_TASKS;
  const int rowSize = MINIDXNN_ROW_SIZE;
  const int columnSize = MINIDXNN_COLUMN_SIZE;
  const dx::linalg::MatrixLayoutEnum weightMatrixLayout = (dx::linalg::MatrixLayoutEnum)MINIDXNN_WEIGHT_MATRIX_LAYOUT;
  const bool isWeightMatrixTransposed = MINIDXNN_WEIGHT_MATRIX_IS_TRANSPOSED != 0;
  const uint matrixVectorStrideAlignment = MINIDXNN_MATRIX_VECTOR_STRIDE_ALIGNMENT;
  using InputVecT = vector<Type, columnSize>;
  using OutputVecT = vector<Type, rowSize>;
  using VectorBufferAccessorT = mininn::impl::VectorBufferAccessor<Type>;

  if (numTasks <= threadId)
    return;

  // Load the inputs
  const InputVecT input = VectorBufferAccessorT::template load<columnSize>(InputBuffer, threadId * sizeof(InputVecT));

  // Create a matrix reference
  using WeightRefT = mininn::MatrixData<mininn::CacheMethod::CACHE>::Ref<ByteAddressBuffer, elemType, weightMatrixLayout, 1, 1, matrixVectorStrideAlignment>;
  using DxMatrixT = typename WeightRefT::template DxMatrixRef<rowSize, columnSize, isWeightMatrixTransposed>;
  const uint32_t2 matrixSize = {0, 0}; // it's not used in this test
  WeightRefT weightBuffer = {WeightBuffer, 0u, matrixSize};
  DxMatrixT matrix = weightBuffer.template makeDxMatrixRef<rowSize, columnSize, isWeightMatrixTransposed>(0);

  OutputVecT output = (OutputVecT)0;
  using LinAlg = mininn::impl::LinearAlgebra;
#if defined(MINIDXNN_HAS_BIAS) && (MINIDXNN_HAS_BIAS != 0)
  // Create a bias reference
  using BiasT = mininn::impl::VectorRefImpl<ByteAddressBuffer, elemType, BIAS_VECTOR_ALIGNMENT>;
  BiasT bias = {BiasBuffer, 0};

  output = LinAlg::mulAdd<Type>(matrix, input, bias);
#else // MINIDXNN_HAS_BIAS
  output = LinAlg::mul<Type>(matrix, input);
#endif // MINIDXNN_HAS_BIAS

  // Store the result
  VectorBufferAccessorT::template store<rowSize>(OutputBuffer, threadId * sizeof(OutputVecT), output);
}

template <typename Type>
void testLinearAlgebraVectorAcc(const uint threadId)
{
  const dx::linalg::ComponentEnum elemType = mininn::impl::TypeTraits<Type>::COMPONENT_TYPE;
  const uint numTasks = MINIDXNN_NUM_TASKS;
  const int size = MINIDXNN_COLUMN_SIZE;
  using InputVecT = vector<Type, size>;

  if (numTasks <= threadId)
    return;

  // Init the inputs
  InputVecT input;
  for (int i = 0; i < size; ++i) {
    input[i] = (Type)(1u << i);
  }

  // test
  mininn::impl::RWVectorRef<elemType, BIAS_VECTOR_ALIGNMENT> output = {OutputBuffer, 0};
  mininn::impl::LinearAlgebra::vectorAcc(input, output);
}

[numthreads(MINIDXNN_NUM_THREADS_X, 1, 1)]
void testLinearAlgebraMulF32Kernel(const uint3 groupThreadId : SV_GroupThreadID, const uint3 groupId : SV_GroupID)
{
  const uint threadId = groupId.x * MINIDXNN_NUM_THREADS_X + groupThreadId.x;
  testLinearAlgebraMul<float32_t>(threadId);
}

[numthreads(MINIDXNN_NUM_THREADS_X, 1, 1)]
void testLinearAlgebraMulF16Kernel(const uint3 groupThreadId : SV_GroupThreadID, const uint3 groupId : SV_GroupID)
{
  const uint threadId = groupId.x * MINIDXNN_NUM_THREADS_X + groupThreadId.x;
  testLinearAlgebraMul<float16_t>(threadId);
}

[numthreads(MINIDXNN_NUM_THREADS_X, 1, 1)]
void testLinearAlgebraVectorAccF32Kernel(const uint3 groupThreadId : SV_GroupThreadID, const uint3 groupId : SV_GroupID)
{
  const uint threadId = groupId.x * MINIDXNN_NUM_THREADS_X + groupThreadId.x;
  testLinearAlgebraVectorAcc<float32_t>(threadId);
}

[numthreads(MINIDXNN_NUM_THREADS_X, 1, 1)]
void testLinearAlgebraVectorAccF16Kernel(const uint3 groupThreadId : SV_GroupThreadID, const uint3 groupId : SV_GroupID)
{
  const uint threadId = groupId.x * MINIDXNN_NUM_THREADS_X + groupThreadId.x;
  testLinearAlgebraVectorAcc<float16_t>(threadId);
}
