/*!
  \file linear_algebra_test.comp
  \author Sho Ikeda
  \brief Test kernel for MLP inference with FP16
  \copyright Copyright (c) 2026 Advanced Micro Devices, Inc. All Rights Reserved.

  SPDX-License-Identifier: MIT
*/

#include "mlp.hlsl"

ByteAddressBuffer InputBuffer;
RWByteAddressBuffer OutputBuffer;
ByteAddressBuffer WeightBuffer;
ByteAddressBuffer BiasBuffer;


template <typename Type>
void testLinearAlgebraMul(const uint groupId, const uint groupThreadId)
{
  const dx::linalg::DataType elemType = mininn::impl::TypeTraits<Type>::COMPONENT_TYPE;
  const uint numThreadsX = MINIDXNN_NUM_THREADS_X;
  const uint numTasks = MINIDXNN_NUM_TASKS;
  const int rowSize = MINIDXNN_ROW_SIZE;
  const int columnSize = MINIDXNN_COLUMN_SIZE;
  const dx::linalg::MatrixLayout weightMatrixLayout = (dx::linalg::MatrixLayout)MINIDXNN_WEIGHT_MATRIX_LAYOUT;
  const bool isWeightMatrixTransposed = MINIDXNN_IS_WEIGHT_MATRIX_TRANSPOSED != 0;
  const uint matrixStrideAlignment = MINIDXNN_MATRIX_STRIDE_ALIGNMENT;
  using InputVecT = vector<Type, columnSize>;
  using OutputVecT = vector<Type, rowSize>;
  using BufferManipT = mininn::impl::BufferManip<Type>;

  const uint threadId = groupId * numThreadsX + groupThreadId;
  if (numTasks <= threadId)
    return;

  // Load the inputs
  const InputVecT input = BufferManipT::template loadVec<columnSize>(InputBuffer, threadId * sizeof(InputVecT));

  // Multiply the weight by the input 
  OutputVecT output = (OutputVecT)0;

  // Create a matrix reference
  using MatrixT = dx::linalg::MatrixRef<elemType, rowSize, columnSize, weightMatrixLayout, isWeightMatrixTransposed>;
  const uint stride = mininn::impl::getWeightMatrixStride<rowSize, columnSize, elemType, weightMatrixLayout, matrixStrideAlignment>();
  MatrixT matrix = {WeightBuffer, 0, stride};

  using LinAlg = mininn::impl::LinearAlgebra;
#if defined(MINIDXNN_HAS_BIAS) && (MINIDXNN_HAS_BIAS != 0)
  // Create a bias reference
  using BiasT = dx::linalg::VectorRef<elemType>;
  BiasT bias = {BiasBuffer, 0};

  output = LinAlg::mulAdd<Type>(matrix, dx::linalg::MakeInterpretedVector<elemType>(input), bias);
#else // MINIDXNN_HAS_BIAS
  output = LinAlg::mul<Type>(matrix, dx::linalg::MakeInterpretedVector<elemType>(input));
#endif // MINIDXNN_HAS_BIAS

  // Store the result
  BufferManipT::template storeVec<rowSize>(OutputBuffer, threadId * sizeof(OutputVecT), output);
}

[numthreads(MINIDXNN_NUM_THREADS_X, 1, 1)]
void testLinearAlgebraMulF32Kernel(const uint3 groupThreadId : SV_GroupThreadID, const uint3 groupId : SV_GroupID)
{
  testLinearAlgebraMul<float32_t>(groupId.x, groupThreadId.x);
}

[numthreads(MINIDXNN_NUM_THREADS_X, 1, 1)]
void testLinearAlgebraMulF16Kernel(const uint3 groupThreadId : SV_GroupThreadID, const uint3 groupId : SV_GroupID)
{
  testLinearAlgebraMul<float16_t>(groupId.x, groupThreadId.x);
}
